# Generated by Django 5.1.4 on 2026-07-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('popular', 'Populares en Netflix'), ('trending', 'Tendencias ahora'), ('mylist', 'Mi lista')], default='popular', max_length=20)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('is_hero', models.BooleanField(default=False, help_text='Si se activa, esta película se muestra en el banner principal.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
